### PR TITLE
Added more images in Land usage Images

### PR DESCRIPTION
**Pull request by anirudhsai20**
#### Issue Number
ISSUE #25

#### Describe the changes you've made
I have added a dataset of images called 'Land scape images' in the 'Land usage Images' folder. It includes numerous images of different types of land scapes which can be used to train a Machine Learning model.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [x] Participating in SWOC2021.
- [x] Participating in DWOC.

### CODE REVIEW

**Review by kahanikaar — CHANGES_REQUESTED** [review]
Do write a proper PR Description on the contribution you are making.

**Comment by anirudhsai20** [comment]
Hi @kahanikaar . I have added a dataset of images called 'Land scapes' in the Land usage Images folder.

**Comment by kahanikaar** [comment]
> Hi @kahanikaar . I have added a dataset of images called 'Land scapes' in the Land usage Images folder.

Refer to PR  #32 and have a proper PR description with Issue Reference and removal of unrelated lines.

**Comment by anirudhsai20** [comment]
@kahanikaar . I have made the necessary changes.

**Comment by anirudhsai20** [comment]
Thank you @kahanikaar !

**Pull request merged**
