### PR TITLE
made the DWoC logo smaller

### PR DESCRIPTION
**Pull request by Sloth-Panda**
#### Issue Number
ISSUE #

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshot (17)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Participating in SWOC2021.
- [ ] Participating in DWOC.

### CODE REVIEW

**Review by kahanikaar — COMMENTED** [review]
Make the details paragraph and the logo inline.

**Comment by kahanikaar** [comment]
Merge this PR with #28

**Comment by kahanikaar** [comment]
@Sloth-Panda Make a complete PR for the issue at once.

**Comment by Sloth-Panda** [comment]
should i create a new branch then

**Comment by Sloth-Panda** [comment]
Hey, I am inexperienced so confused about why this is showing to resolve conflicts above and also make a complete PR means do I need to create a new branch and do the work over there. Please explain a bit .

**Comment by kahanikaar** [comment]
> should i create a new branch then

Go ahead

**Comment by kahanikaar** [comment]
> Hey, I am inexperienced so confused about why this is showing to resolve conflicts above and also make a complete PR means do I need to create a new branch and do the work over there. Please explain a bit .

Corrected that!

**Pull request closed without merging**
