### PR TITLE
Added dwoc and swoc to to readme and made them come inline 

### PR DESCRIPTION
**Pull request by Sloth-Panda**
#### Issue Number
ISSUE #23 

Screenshot (18)

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Participating in SWOC2021.
- [x] Participating in DWOC.

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
All looks good ig if still want some improvement do tell and can you tell me why these conflicts are showing??

**Comment by kahanikaar** [comment]
Do pull the current repository and make  the changes and make the PR, or work in #29, otherwise you will be facing the stated conflicts.

**Comment by Sloth-Panda** [comment]
Can you check it now I just resolved the conflict

**Review by kahanikaar — CHANGES_REQUESTED** [review]
Looks good to me! Just try to make the paragraph size as per the orientation of readme in github, 
In readme markdown, still the logo goes after the paragraph at the bottom. 
Review requested @07souravkunda

**Review by 07souravkunda — APPROVED** [review]

**Comment by Sloth-Panda** [comment]
This looks like this rn

**Comment by kahanikaar** [comment]
Merging! Thanks for the contribution!

**Comment by Sloth-Panda** [comment]
Screenshot (19)
It looks like this rn

**Pull request merged**
