### PR TITLE
Added SignIn and SignUp Components.

### PR DESCRIPTION
**Pull request by sanjay270899**
#### Issue Number
ISSUE #13 

#### Describe the changes you've made
Made Sign Up and Sign In Components.
Both components are responsive.
Added validation in both components.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
`NA`

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Participating in SWOC2021.
- [x] Participating in DWOC.

### CODE REVIEW

**Comment by sanjay270899** [comment]
You can see my work at the below link,
https://sanjay270899.github.io/Realate/

**Comment by sanjay270899** [comment]
@07souravkunda Please review it, and let me know if any changes needed.

**Review by 07souravkunda — COMMENTED** [review]
@sanjay270899 you have done a great work. I like your work. You have maintained good folder structure. stylings are nice. Keep contributing.

**Comment by 07souravkunda** [comment]
You can place utils folder on app.js level

**Comment by sanjay270899** [comment]
> You can place utils folder on app.js level

Oh Yes! I didn't notice that. Changing that quickly.

**Review by 07souravkunda — APPROVED** [review]

**Pull request merged**
