### PR TITLE
#38 Layout Component frontend

### PR DESCRIPTION
**Pull request by Kathuria**
ISSUE #38

#### Describe the changes you've made
Created Layout Component using background image with shared LayoutBG.jpg. Now can add components upon it.

#### Describe if there is any unusual behavior of your code
Not able to access public images, a lot of articles which says you cannot access files outside src. Need to **eject** thus to avoid this applied alternative approach and making it safer - added assets folder in src with copied LayoutBG.jpg - to access as src assets.

#### Checklist
- [x] My code follows the code style of this project.
- [x] I have read the **[CONTRIBUTING] guidelines mentioned in repo.
- [x] Participating in SWOC2021.

### CODE REVIEW

**Review by 07souravkunda — COMMENTED** [review]
Header component will be above the Layout component. Layout component should have 100% width and height. Add a 0.4 opacity black dropdown above the background image. Please make the changes accordingly.

**Comment by 07souravkunda** [comment]
There is no problem in keeping images inside src.

**Comment by Kathuria** [comment]
@07souravkunda : Please check now.

**Comment by Kathuria** [comment]
@07souravkunda Done

**Pull request merged**
